### ISSUE TITLE
Error in pipeline unittest after setup

### ISSUE THREAD

**Issue by mbehrooz** [google/seq2seq#316]
I initially encountered Bernoulli and Categorical import errors. I fixed that by doing the solutions in #285. But now I get a new error: (I have tf 1.5.0 rc-1)

======================================================================
ERROR: test_train_infer (seq2seq.test.pipeline_test.PipelineTest)
Tests training and inference scripts.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/morteza/seq2seq/seq2seq/seq2seq/test/pipeline_test.py", line 76, in test_train_infer
    _clear_flags()
  File "/home/morteza/seq2seq/seq2seq/seq2seq/test/pipeline_test.py", line 44, in _clear_flags
    tf.app.flags.FLAGS = tf.app.flags._FlagValues()
AttributeError: module 'tensorflow.python.platform.flags' has no attribute '_FlagValues'

**Comment by Shimin-Zhang** [comment]
Incase you are still stuck, took me a bit but this finally worked: 
```

# tf.app.flags.FLAGS = tf.app.flags._FlagValues()
attr_names = []
for i in tf.app.flags.FLAGS:
    names.append(i)
for n in attr_names:
    delattr(tf.app.flags.FLAGS, n)
```

**Comment by ivokwee** [comment]
probably this was a mistake?

```
    attr_names.append(i)
```

**Comment by cameronrhamilton** [comment]
I am also facing this same error while using Tensorflow 1.7. @JohnSZhang 's suggestion eliminated the initial error, but now I'm encountering a DuplicateFlagError, which suggests the flags are not actually getting cleared. Any suggestions?

**Comment by slvher** [comment]
tf.app.flags.FLAGS is defined in (take the codebase of tf v1.5 as example):
https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/python/platform/flags.py

It's a wrapper for FlagValues which defined in:
https://github.com/abseil/abseil-py/blob/master/absl/flags/_flagvalues.py

After reading the source code, i modified the function body of _clear_flags and the error gone away.  
The hacking snippet looks like this:

```
def _clear_flags():
    """Resets Tensorflow's FLAG values"""
    #pylint: disable=W0212
    for flag_key in dir(tf.app.flags.FLAGS):
        delattr(tf.app.flags.FLAGS, flag_key)
    #tf.app.flags.FLAGS = tf.app.flags._FlagValues()
    tf.app.flags._global_parser = argparse.ArgumentParser()
```
@cameronrhamilton  Hope can help you :)

**Comment by cameronrhamilton** [comment]
Thank you @slvher !  I am unfortunately still receiving the following error:
`DuplicateFlagError: The flag 'model_params' is defined twice. First from seq2seq.test.train_bin, Second from seq2seq.test.infer_bin.  Description from first occurrence: YAML configuration string for the model parameters.`
I am investigating to determine how to fix this, but have not made much progress.

**Comment by onlyjackfrost** [comment]
I got a problem after i  solved the #285 and the AttributeError which @mbehrooz  mentioned above
I used the command  `python -m unittest seq2seq.test.pipeline_test` and i got a error below

```
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpi7s9txub'
       
 [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0",
_device="/job:localhost/replica:0/task:0/device:CPU:0"](bleu/sources/read, bleu/targets/read)]]
```

I've check the path"C:\\Users\\user\\AppData\\Local\\Temp" and there is no such file...
Btw im using Anaconda for python3.6 and tensorflow1.8 on window8.1

**Comment by neerajks** [comment]
Hi any luck resolving the above error ? I am facing the same error on tensorflow 1.8.

**Comment by nciefeiniu** [comment]
@neerajks I have the same problem，

tensorflow and python version:
1.8.0 v1.8.0-0-g93bc2e2072 /usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py

OS: ubuntu 16.04



Now ,The problem has been solved
thanks @slvher

**Comment by awonderfullife** [comment]
I think I have sloved all these error  (ImportError, _FlagValues error and _tkinter.TclError) : 
You could referenced this link:
https://blog.csdn.net/cow66/article/details/80815394
@neerajks @nciefeiniu

**Comment by misswang1221** [comment]
> I got a problem after i solved the #285 and the AttributeError which @mbehrooz mentioned above
> I used the command `python -m unittest seq2seq.test.pipeline_test` and i got a error below
> 
> ```
> PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpi7s9txub'
>        
>  [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0",
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](bleu/sources/read, bleu/targets/read)]]
> ```
> I've check the path"C:\Users\user\AppData\Local\Temp" and there is no such file...
> Btw im using Anaconda for python3.6 and tensorflow1.8 on window8.1



> I got a problem after i solved the #285 and the AttributeError which @mbehrooz mentioned above
> I used the command `python -m unittest seq2seq.test.pipeline_test` and i got a error below
> 
> ```
> PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpi7s9txub'
>        
>  [[Node: bleu/value = PyFunc[Tin=[DT_STRING, DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0",
> _device="/job:localhost/replica:0/task:0/device:CPU:0"](bleu/sources/read, bleu/targets/read)]]
> ```
> I've check the path"C:\Users\user\AppData\Local\Temp" and there is no such file...
> Btw im using Anaconda for python3.6 and tensorflow1.8 on window8.1

I got a same error. [PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\tmpzvxkn3wu']

**Comment by Mehty** [comment]
> @neerajks I have the same problem，
> 
> tensorflow and python version:
> 1.8.0 v1.8.0-0-g93bc2e2072 /usr/local/lib/python3.5/dist-packages/tensorflow/**init**.py
> 
> OS: ubuntu 16.04
> 
> Now ,The problem has been solved
> thanks @slvher

Any suggestions on how to fix this problem? I am working on windows 10, and I tried with the specified tf+python version above and still get the same error. I appreciate any help

**Comment by sehargul-123** [comment]
Traceback (most recent call last):
File "DeepSpeech.py", line 11, in
import absl.app
File "/home/sehar/venv/lib/python3.6/site-packages/absl/app.py", line 40, in
from absl import flags
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/init.py", line 41, in
from absl.flags import _defines
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_defines.py", line 31, in
from absl.flags import _flagvalues
File "/home/sehar/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 27, in
import logging
File "/home/sehar/DeepSpeech/logging.py", line 6, in
from util.flags import FLAGS
File "/home/sehar/DeepSpeech/util/flags.py", line 6, in
FLAGS = absl.flags.FLAGS
AttributeError: module 'absl' has no attribute 'flags'
kindly help me to slove this error

**Comment by sehargul-123** [comment]
please help me in this above issue I have been using tensorflow-gpu 1.14
